# Generated by Django 4.0 on 2022-07-09 12:32

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='HostelRoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostel_name', models.CharField(max_length=50)),
                ('Hostel_type', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(max_length=200)),
                ('rating', models.FloatField(null=True)),
                ('food', models.BooleanField(default=False)),
                ('pg', models.BooleanField(default=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('details', models.CharField(max_length=500, null=True)),
                ('facility1', models.CharField(max_length=50, null=True)),
                ('facility2', models.CharField(max_length=50, null=True)),
                ('facility3', models.CharField(max_length=50, null=True)),
                ('facility4', models.CharField(max_length=50, null=True)),
                ('facility5', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('stars', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomCatecoryName', models.CharField(max_length=100)),
                ('sharing', models.IntegerField()),
                ('roomCount', models.IntegerField()),
                ('amountFor_10_days', models.IntegerField()),
                ('amountFor_20_days', models.IntegerField()),
                ('amountFor_a_month', models.IntegerField()),
                ('rating', models.FloatField()),
                ('roomMainImage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('details', models.CharField(max_length=500, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostels')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsForRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('stars', models.FloatField()),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.rooms')),
            ],
        ),
    ]
